export const experienceData = [
  {
    id: 1,
    time: '2023 - To Present',
    img: '/images/Woodkraft.png',
    imgWidth: 208,
    bg: 'bg-rose-50',
    borderColor: 'border-rose-100',
    title: 'Woodkraft India',
    description: 'Building Future-Ready Data Centers & Fabs',
  },
  {
    id: 2,
    time: '2019 - 2023',
    img: '/images/Hippo-Stores-logo.png',
    imgWidth: 60,
    bg: 'bg-emerald-50',
    borderColor: 'border-emerald-100',
    title: 'Hippo Stores',
    description: `Building India's First Wholesale Revolution`,
  },
  {
    id: 3,
    time: '2013 - 2019',
    img: '/images/Fitart-logo.png',
    imgWidth: 38,
    bg: 'bg-lime-50',
    borderColor: 'border-lime-100',
    title: 'Fitart',
    description: 'Crafting Dreams, One Home at a Time',
  },
  {
    id: 4,
    time: '2007 - 2013',
    img: '/images/Walmart_logo.png',
    imgWidth: 157,
    bg: 'bg-violet-50',
    borderColor: 'border-violet-100',
    title: 'Walmart India / Bharti Walmart',
    description: 'Scaling New Heights in Retail',
  },
  {
    id: 5,
    time: '2006 - 2007',
    img: '/images/AT-Kearney-logo.png',
    imgWidth: 183,
    bg: 'bg-rose-50',
    borderColor: 'border-rose-100',
    title: 'AT Kearney',
    description: 'The Strategy Maverick',
  },
  {
    id: 6,
    time: '2003 - 2006',
    img: '/images/technopak.png',
    imgWidth: 115,
    bg: 'bg-emerald-50',
    borderColor: 'border-emerald-100',
    title: 'KSA Technopak',
    description: 'Laying the Groundwork for Retail’s Future',
  },
  {
    id: 7,
    time: '1994 - 2001',
    img: '/images/Draeger.png',
    imgWidth: 99,
    bg: 'bg-violet-50',
    borderColor: 'border-violet-100',
    title: 'Drager India',
    description: 'Redefining Healthcare Solutions',
  },
];
