export const experienceDetailData = [
  {
    id: 1,
    year: '2023 - Present',
    yclr: 'rgba(6,82,176,1)',
    btnclr: 'rgba(2,113,248,0.2)',
    bdrclr: 'rgba(2,113,248,0.07)',
    company: 'Woodkraft India',
    title: 'Building Future-Ready Data Centers & Fabs',
    description:
      'In 2023, I got a very unique opportunity to assess the largest office interiors business and chart out a new growth plan for the company. After identifying the core growth sectors I embarked on the journey to create capabilities within the organization to become an integrated design, engineering and construction company.',
    highlights: [
      'Opened a new company focused on data centers and clean environments',
      'Did a joint venture with a construction company for delivering CSA scope of projects',
      'Made strategic investment in an MEP design company',
      'Opened an electrical contracting company with intent to keep labour on rolls to deliver mission critical projects',
      'Rebranded the business to deliver on the new focus',
      'Identified Data Centers, Semiconductor fabs, Research Laboratories, Hospitals, Education and Commercial Offices as focus segments',
      'Shortlisted by AWS, STT, NTT, Google, Max Hospitals, AIG Hospitals, Narayana Healthcare',
      'Resulted in an order book of Rs. 800 Crore',
    ],
  },
  {
    id: 2,
    year: '2019 - 2023',
    yclr: 'rgba(145,92,3,1)',
    btnclr: 'rgba(236,183,94,0.3)',
    bdrclr: 'rgba(236,183,94,0.2)',
    company: 'Hippo Stores',
    title: `Building India's First Wholesale Revolution`,
    description:
      'In 2019, I found myself at the helm of a vision no one had dared to attempt in India—a building product wholesale business on a scale that had never been seen before. As Senior Vice President – Sales and Marketing, I was entrusted with the immense responsibility of launching this pioneering venture under the Dalmia Bharat Group.',
    highlights: [
      'Audacious idea: create a marketplace for builders, resellers, and contractors to access 12,000+ products under one roof.',
      'Launched a seamless B2B app for digital interaction.',
      'Achieved a 250 Crore annual run rate within a year.',
      'Gained 6,000 customers and built an 80+ strong digitally empowered sales team.',
      'Focused on transforming convenience, trust, and growth for India’s builders and wholesalers.',
    ],
  },
  {
    id: 3,
    year: '2013 - 2019',
    yclr: 'rgba(5,73,47,1)',
    btnclr: 'rgba(20,189,124,0.3)',
    bdrclr: 'rgba(20,189,124,0.2)',
    company: 'FitArt',
    title: 'Crafting Dreams, One Home at a Time',
    description:
      'In 2013, I ventured into entrepreneurship. FITART was born not just as a modular furniture manufacturer but as a vision to bring art into everyday living. I set up a state-of-the-art manufacturing facility that redefined customization, bringing German precision to Indian homes and retail spaces.',
    highlights: [
      'Built FITART, focusing on more than just furniture—crafted stories and emotions.',
      'Delivered premium home projects for clients like Yuvraj Singh and Virat Kohli.',
      `Created niche retail environments for brands like Tanishq and Dunkin' Donuts.`,
      `Achieved 600+ satisfied home clients and completed 30+ turnkey retail projects.`,
      `FITART became a space where dreams met reality, combining craftsmanship, creativity, and trust.`,
    ],
  },
  {
    id: 4,
    year: '2007 - 2013',
    yclr: 'rgba(173,68,83,1)',
    btnclr: 'rgba(252,149,164,0.3)',
    bdrclr: 'rgba(252,149,164,0.4)',
    company: 'Walmart / Bharti Walmart',
    title: 'Scaling New Heights in Retail',
    description:
      '2007 was a turning point. Joining Walmart, the world’s largest retailer, I was tasked with something monumental: to bring their retail magic to India. As Executive Vice President, I had the honor of leading the launch of three diverse formats across India—Easy Day, Easy Day Market, and Best Price.',
    highlights: [
      `Launched 320+ stores across various formats, contributing to India's evolving retail ecosystem.`,
      `Each store was more than just a business; it was a gateway to global standards with local relevance.`,
      `By 2013, 280+ Easy Day stores had opened, transforming everyday shopping into an extraordinary experience.`,
    ],
  },
  {
    id: 5,
    year: '2006 - 2007',

    yclr: 'rgba(53,103,117,1)',
    btnclr: 'rgba(100,192,217,0.3)',
    bdrclr: 'rgba(100,192,217,0.4)',
    company: 'AT Kearney',
    title: 'The Strategy Maverick',
    description:
      'Before Walmart, I took on a role that would shape the way I approached business strategy forever. As Director of Retail and Consumer Goods Practice at A.T. Kearney, I led transformative projects that redefined the retail landscape for some of India’s biggest players.',
    highlights: [
      'Taking revenue from $150K to $6 million in just a year wasn’t just a metric of success',
      'It was proof of what happens when innovation meets execution.',
      `Marquee Projects - Reliance group's Retail Business Plan, Aditya Birla group's retail strategy and implementation, Walmart's India Entry`,
    ],
  },
  {
    id: 6,
    year: '2003 - 2006',
    yclr: 'rgba(68,68,146,1)',
    btnclr: 'rgba(131,131,255,0.3)',
    bdrclr: 'rgba(131,131,255,0.2)',
    company: 'KSA Technopak',
    title: `Laying the Groundwork for Retail’s Future`,
    description:
      'The world of retail was calling, and in 2003, I answered by joining KSA Technopak. Establishing their Bangalore office, I had the privilege of working on transformative projects that would shape Indian retail as we know it today. Working across continents, from London’s Sainsbury to India’s Reliance Retail, my role was about building bridges—bridges between strategy and action, between global trends and local needs.',
    highlights: [
      'Worked in London for an year in London on projects for Sainsbury, Early Learning Centre, Mothercare and MFI (Furniture retailer)',
      'Established the Bangalore office of KSA focused on retail implementation practice',
      'Key Clients Apollo Pharmacy, Essar Group Mobile Retail, Godrej Aadhaar Retail, Reliance Retail and Birla Retail ',
    ],
  },
  {
    id: 7,
    year: '1994 - 2001',
    yclr: 'rgba(145,92,3,1)',
    btnclr: 'rgba(236,183,94,0.3)',
    bdrclr: 'rgba(236,183,94,0.2)',
    company: 'Usha Draeger Ltd',
    title: 'Redefining Healthcare Solutions',
    description:
      'Every journey has a beginning, and mine started at Usha Drager Ltd, where I headed their Medical Architectural Products division. Bringing cutting-edge medical infrastructure to India, I not only exceeded sales targets year after year but also established UDL as the market leader in medical gas pipelines. My role wasn’t just about products; it was about bringing life-saving technology to hospitals across India.',
    highlights: [
      'Exceeded my Sales target each year. Was awarded the best sales person award each year.',
      'Established the Medical Architectural (gas pipeline) business in IndiaWas selected to go to Dragerwerk Ag Germany for an year of training on medical architectural systems.',
      'Within 12 months UDL was the market leader in the sector with total business contribution of 40% of the entire business of UDL.',
      `New Products added by identifying international companies and negotiating India market representation agreements : Mobile Intensive Care Units, Premium Range of Hospital Beds, Crash Carts, Syringe and Infusion Pumps.`,
      `In the first year itself the business contribution was over 15% of the business. Today the Syringe and Infusion Pumps are no. 1 in India.`,
    ],
  },
];
